repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: fb24a639f7c938759fe56eeebbb7713b69d60494 # v0.5.1
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-imports
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy

  - repo: https://github.com/golangci/golangci-lint
    rev: 9aa24e94ceb7d1a8ccbde81e7424629467299a7e # v2.12.1
    hooks:
      - id: golangci-lint
